# Generated by Django 3.0.4 on 2020-03-13 02:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 2, 21, 6, 504858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 2, 21, 6, 504065, tzinfo=utc)),
        ),
    ]
